export const ADS_LIST_REQUEST = "ADS_LIST_REQUEST";
export const ADS_LIST_SUCCESS = "ADS_LIST_SUCCESS";
export const ADS_LIST_FAIL = "ADS_LIST_FAIL";

// create
export const ADS_CREATE_REQUEST = "ADS_CREATE_REQUEST";
export const ADS_CREATE_SUCCESS = "ADS_CREATE_SUCCESS";
export const ADS_CREATE_FAIL = "ADS_CREATE_FAIL";

//update
export const ADS_UPDATE_REQUEST = "ADS_UPDATE_REQUEST";
export const ADS_UPDATE_SUCCESS = "ADS_UPDATE_SUCCESS";
export const ADS_UPDATE_FAIL = "ADS_UPDATE_FAIL";

// delete
export const ADS_DELETE_REQUEST = "ADSS_DELETE_REQUEST";
export const ADS_DELETE_SUCCESS = "ADSS_DELETE_SUCCESS";
export const ADS_DELETE_FAIL = "ADSS_DELETE_FAIL";
