export const USER_LOGIN_REQUEST = "USER_LOGIN-REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN-SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN-FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER-REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER-SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER-FAIL";
